name: quick_blue_example
description: Demonstrates how to use the quick_blue plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  quick_blue:
    # When depending on this package from a real application you should use:
    #   quick_blue: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../quick_blue

  cupertino_icons: ^1.0.0
  convert: ^3.0.0
  logging: ^1.0.2
  permission_handler: '>=9.0.0 <15.0.0'
  http: ^1.1.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  quick_blue_platform_interface:
    path: ../quick_blue_platform_interface
  quick_blue_windows:
    path: ../quick_blue_windows
  quick_blue_macos:
    path: ../quick_blue_macos
  quick_blue_linux:
    path: ../quick_blue_linux

flutter:
  uses-material-design: true